# Generated by Django 4.1.1 on 2022-12-12 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='out',
            old_name='name',
            new_name='description',
        ),
    ]
