# Generated by Django 4.1.1 on 2022-12-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_in_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in',
            name='category',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='out',
            name='category',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
