# Generated by Django 4.1.1 on 2022-12-19 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_in_category_out_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('user_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.in')),
                ('user_out', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.out')),
            ],
        ),
    ]
