# Generated by Django 4.1.1 on 2022-12-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_in_user_out_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in',
            name='user',
        ),
        migrations.RemoveField(
            model_name='out',
            name='user',
        ),
    ]
