# Generated by Django 4.1.1 on 2022-12-30 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_in_user_in_alter_out_user_out'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
