# Generated by Django 4.1.1 on 2023-08-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_in_user_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in',
            name='category',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='in',
            name='description',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='out',
            name='category',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='out',
            name='description',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
