# Generated by Django 4.1.1 on 2024-01-23 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_in_category_alter_in_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in',
            name='amount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='out',
            name='amount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
